[package]
authors = ["Reece Stevens <reecestevens24@gmail.com>"]
name = "digital-filter"
version = "0.1.0"

[dependencies]
generic-array = "0.11.1"
typenum = "1.10.0"

[dependencies.heapless]
git = "https://github.com/ReeceStevens/heapless"
