[package]
authors = ["Reece Stevens <reecestevens24@gmail.com>"]
name = "digital-filter"
version = "0.3.0-alpha.1"
description = "A simple digital filter library"
license = "MIT"

[dependencies]
heapless = "0.7.1"
